import type { Metadata } from "next"
import "./globals.css"

import ReactQueryProvider from "@/providers/ReactQueryProvider"
import { Toaster } from "sonner"

export const metadata: Metadata = {
  title: "App",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          {children}
        </ReactQueryProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  )
}