import type { Metadata } from "next"
import { Roboto } from "next/font/google";
import "./globals.css"

import ReactQueryProvider from "@/providers/ReactQueryProvider"
import { Toaster } from "sonner"

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "App",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en"  className={roboto.variable}>
      <body>
        <ReactQueryProvider>
          {children}
        </ReactQueryProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  )
}